
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('pets').del()
    .then(function () {
      // Inserts seed entries
      return knex('pets').insert([
        { status: 'Available',
    age: 'Adult',
    size: 'XL',
    breed: 'Pit Bull Terrier',
    name: 'Coco',
    sex: 'Female',
    description: 'Coco can think of nothing she would enjoy more than a household where she could have love pretty much all the time. Yes, she is that responsive and loving with humans. That said, she is getting along famously with her resident foster dog sibling and they are finding it fun to play keep-away and tug with toys, so she\'s got a playful streak as well. Coco is fully house trained and appears crate trained, too. However, unless a human wants to be in there with her, she would much prefer to be out and about with her family than in her crate. She does get a titch restless if left alone in the crate for too long. Coco has spurts of energy when play is her first agenda, but she would be very happy in a home where there\'s far more snuggle and chill out time than busy activity time. She\'s a happy go lucky gal; all you have to do is look her way and her tail starts spinning in glee. Oh, since she is so well adjusted to life as she knows it, I forgot to mention that she is a tripod, one who gets along very well with three legs. Come meet Coco today, she doesn\'t want you to lose out on any more time to pet and snuggle with her. June 30, 2017, 4:22 am',
    petID: '17947520',
    type: 'Dog',
    photo: 'http://photos.petfinder.com/photos/pets/17947520/1/?bust=1497394914&width=500&-x.jpg' },
  { status: 'Available',
    age: 'Senior',
    size: 'L',
    breed: 'German Shepherd Dog',
    name: 'Ranger Rick',
    sex: 'Male',
    description: 'Some have said Ranger Rick resembles a giant chihuahua - this does not faze Ranger Rick one bit! He is an absolutely adorable smart-as-a-whip mature guy who knows who he is. Although he does not deny that he may have a very distant cousin who at one time dated a chihuahua! He is a volunteer favorite and often hears the ooh and aahs of people who meet him. With his adorable looks and sweet personality, Ranger Rick will put a smile on your face. Ranger Rick can be a very goofy boy. He loves playing fetch with a tennis ball and will enjoy running around the yard with you. He likes going on walks and exploring. Ranger Rick also has a very sensitive side and genuinely appreciates affection from his humans. Ranger Rick walks very well on leash and is polishing up his \'place\' and \'come\' commands. He is super smart and enjoys his training sessions as they keep his mind active and is in the Total Obedience Program. The Total Obedience Program (TOP) is modelled after the AKC\'s Canine Good Citizen (CGC) test. As a TOP dog, Ranger Rick has a personalized training plan and works with a volunteer trainer several times a week to help him learn the skills to become the best dog he can be! He is learning skills like sit and down, walking nicely on leash, sitting calmly when approached by strangers or other dogs, staying in a sit or down until told \'free,\' and coming when called. Once Ranger Rick successfully completes all the skills on his training plan he will be considered TOP Dog Ready! Ranger Rick is working hard to become a wonderful pet and as a part of APA\'s Total Obedience Program you can work with APA staff to continue to build a training relationship with Ranger Rick after adoption and master all the TOP dog skills together. Check out a video on APA\'s CGC program, on which the TOP was based: https://vimeo.com/89434193 Why not take a chance and come on down to meet the irresistible pup who is looking for his family and forever home!',
    petID: '37295784',
    type: 'Dog',
    photo: 'http://photos.petfinder.com/photos/pets/37295784/1/?bust=1496723431&width=500&-x.jpg' },
  { status: 'Available',
    age: 'Adult',
    size: 'XL',
    breed: 'Hound',
    name: 'Beau',
    sex: 'Male',
    description: 'Beau is a classically handsome hound dog. He loves to do rugged, handsome things like play fetch and pose for photographs. You might assume he is a Clint Eastwood-type, but he is really a goofball. Just watch him try to play fetch by himself, and you will realize there\'s not a whole lot of self-consciousness going on. Beau is house trained, crate trained, walks well on a leash and knows sit. He can be a bit awkward when meeting new people and animals, but he is super affectionate with the people he gets to know, and he has lived with other dogs before. Since he does have some hound in him, he tends to emote very dramatically. \'I have to use the potty\' comes out like an epic, mournful howl to the moon. Beau has been bounced around a bit, but is very ready to settle into a forever home. He\'s a funny guy with a big personality, and even bigger potential. Come meet him!',
    petID: '37295791',
    type: 'Dog',
    photo: 'http://photos.petfinder.com/photos/pets/37295791/1/?bust=1496723444&width=500&-x.jpg' },
  { status: 'Available',
    age: 'Adult',
    size: 'XL',
    breed: 'American Bulldog',
    name: 'Santana',
    sex: 'Female',
    description: 'Long trail hikes? Check. Cuddle forever friend? Check Polite and well mannered? Check. Santana has learned so much in her stay at APA! She\'s accomplished leash walker and takes her volunteer buddy around Lady Bird Lake just about every morning. Her perfect day is a long, leisurely hike followed by a snooze in your lap. She is a perfect lady in the house, and quite a beauty. She is sure to improve your decor just by lying on the couch. Her home skills are being impeccably house trained, a napper and she won\'t snatch anything off the counter. Santana enjoys learning new things and is in the Total Obedience Program. The Total Obedience Program (TOP) is modelled after the AKC\'s Canine Good Citizen (CGC) test. As a TOP dog, Santana has a personalized training plan and works with a volunteer trainer several times a week to help her learn the skills to become the best dog she can be! She is learning skills like sit and down, walking nicely on leash, sitting calmly when approached by strangers or other dogs, staying in a sit or down until told \'free,\' and coming when called. Once Santana successfully completes all the skills on her training plan she will be considered TOP Dog Ready! Santana is working hard to become a wonderful pet and as a part of APA\'s Total Obedience Program you can work with APA staff to continue to build a training relationship with Santana after adoption and master all the TOP dog skills together. Check out a video on APA\'s CGC program, on which the TOP was based: https://vimeo.com/89434193',
    petID: '37295797',
    type: 'Dog',
    photo: 'http://photos.petfinder.com/photos/pets/37295797/1/?bust=1496723456&width=500&-x.jpg' },
  { status: 'Available',
    age: 'Adult',
    size: 'XL',
    breed: { '$t': 'Pointer' },
    name: 'Galaxy',
    sex: 'Female',
    description: 'Galaxy is APA\'s version of Princess Leia with eyes that sparkle brighter than stars in the sky when she sees the people she loves. This affectionate, sometimes goofy girl can be shy when first meeting new humans, but once she gets comfortably acquainted, she lights up and her personality shines. She loves, loves and loves her human friends and wants to cuddle with them, sneaking in kisses and curling up in their laps. Galaxy is happy to take walks and play with toys, then lay next to her people and ask for petting. And if it\'s been a while since you gave her a treat, she\'ll put her paw on your arm as a polite reminder. Galaxy has great leash skills and is crate and house trained. Quick to learn, Galaxy is in the Total Obedience Program. The Total Obedience Program (TOP) is modeled after the AKC\'s Canine Good Citizen (CGC) test. As a TOP dog, Galaxy has a personalized training plan and works with a volunteer trainer several times a week to help her learn the skills to become the best dog she can be! She is now TOP Dog Ready, which means she\'s already learned all the skills in her training plan, including sit and down, walking nicely on leash, sitting calmly when approached by strangers, calmly walking past another dog, staying in a sit or down until told \'free,\' and coming when called. Galaxy has worked hard to become a wonderful pet and as a part of APA\'s Total Obedience Program you can work with APA staff to continue to build a training relationship with Galaxy after adoption and master all the TOP dog skills together. Check out a video on APA\'s CGC program, on which the TOP was based: https://vimeo.com/89434193 Come meet this girl with the cutest, most contagious smile and see if she can be part of your galaxy!',
    petID: '37295800',
    type: 'Dog',
    photo: 'http://photos.petfinder.com/photos/pets/37295800/1/?bust=1496723469&width=500&-x.jpg' },
  { status: 'Available',
    age: 'Adult',
    size: 'XL',
    breed: { '$t': 'Pit Bull Terrier' },
    name: 'Bock',
    sex: 'Male',
    description: 'Good looks? Check! Good manners? Check! Good fetching skills? Check, check check! Bock is one happy dude! He will flirt with his 1,000-watt smile and win you over with his joie de vivre. Then when he\'s sure of your love, he\'ll turn his attention to the other love of his life: balls. Tennis balls, jolly balls (yes, those toys meant for horses), and even a bowling ball he tries to stand on! Bock loves them all! He also really enjoys playing with frisbees and chillin\' in a pool. Don\'t worry, Bock has a soft spot for humans too. As soon as you call him over, he\'s all wiggles and back scratches. He loves to snuggle after a full day of fetch, so get comfortable! This cute chicken (bock bock bock!) is a charmer and would love nothing more than to be your Netflix partner every day of the week. Bock loves learning; he\'s happy to hang up his ball for a little bit while he\'s learning the finer points of obedience at the Total Obedience Program. The Total Obedience Program (TOP) is modeled after the AKC\'s Canine Good Citizen (CGC) test. As a TOP dog, Bock has a personalized training plan and works with a volunteer trainer several times a week to help him learn the skills to become the best dog he can be! He is learning skills like sit and down, walking nicely on leash, sitting calmly when approached by strangers or other dogs, staying in a sit or down until told \'free,\' and coming when called. Once Bock successfully completes all the skills on his training plan he will be considered TOP Dog Ready! Bock is working hard to become a wonderful pet and as a part of APA\'s Total Obedience Program you can work with APA staff to continue to build a training relationship with Bock after adoption and master all the TOP dog skills together. Check out a video on APA\'s CGC program, on which the TOP was based: https://vimeo.com/89434193 Don\'t miss out on the gorgeous dog! Bock is all retriever and will reward long days of fetching with companionship.',
    petID: '37295804',
    type: 'Dog',
    photo: 'http://photos.petfinder.com/photos/pets/37295804/1/?bust=1496723483&width=500&-x.jpg' },
  { status: 'Available',
    age: 'Adult',
    size: 'L',
    breed: 'Australian Cattle Dog / Blue Heeler',
    name: 'Murphy',
    sex: 'Male',
    description: 'Murphy is a true go-getter. He\'s very smart and very athletic. He\'s not just interviewing to be your dog; he\'s interviewing for a job. Whether patrolling your yard for varmints, keeping you safe out on the trails or learning to run obstacle courses, Murphy is happiest when he\'s got something to do. Murphy is house trained, knows sit, and walks well on a leash. He is very protective of his home and the people he loves, so he can be a bit aloof when meeting strangers. He wants to decide for himself if you are friend or foe. But once he decides you are a friend, he\'s ride or die. He\'s as loyal as they come. If you\'re interested in getting into some sporting dog competitions, or if you\'re a regular exerciser looking for a partner, or maybe have a large piece of property in need of protecting, Murphy would love to meet you. He\'s got a five-year plan, a can-do attitude, and he can start immediately.',
    petID: '37295812',
    type: 'Dog',
    photo: 'http://photos.petfinder.com/photos/pets/37295812/1/?bust=1496723497&width=500&-x.jpg' },
  { status: 'Available',
    age: 'Adult',
    size: 'XL',
    breed: 'Border Collie',
    name: 'Major',
    sex: 'Male',
    description: 'Meet Major, a vivacious, spirited ball of fluff. This silly guy does a cute play bow followed quickly by a zoom around the yard when he wants to play with his human. He can be very cat-like when he wants attention, preferring to rub his head all over your legs. Major is dreaming of finding his forever home, complete with a spacious and secure backyard for him to run around. While he\'d love to find a human that loves to be just as active as him, he is also skilled in the art of \'self-fetch\' by tossing his toys up into the air and catching them with gusto. This smart and treat-motivated pup is the perfect companion for agility training, puzzle toys and games. Major will delight his new family with all kinds of tricks and commands, which you\'ll get to know in pre-adoption training provided by APA. Major is an excellent leash walker and gives great eye contact; he is always ready to listen and learn. Open your heart and home to this smarty-pants and get ready to fall in love with Major\'s adorable ears, and his charming quirkiness and zest for life!',
    petID: '37295814',
    type: 'Dog',
    photo: 'http://photos.petfinder.com/photos/pets/37295814/1/?bust=1497100317&width=500&-x.jpg' },
  { status: 'Available',
    age: 'Adult',
    size: 'XL',
    breed: 'Pit Bull Terrier',
    name: 'Oscar',
    sex: 'Male',
    description: 'Do you like to hit the snooze button a few times in the morning? Oscar does too! This cutie is happy to cuddle in bed until the late morning. He will also politely lounge around the house once he does get up, maybe chewing on a nice bone or stuffed toy. Don\'t let his lazy, homebody attitude fool you though. He is more than happy to join his human for a nice long walk or jog. He also loves swimming and wading in any body of water he can find. At the shelter, Oscar spends his time playing fetch and and going for walks with his favorite volunteers. He has also had lots of behavior training and likes to show off his great leash manners. He spent some time in a foster home where he has proven his love for sleep and snuggling, and impressed his friends by being crate trained and house trained! Oscar bonds closely with his humans and needs a low-key home with a patient and loving individual or couple. He may be able to live with another well-matched pup, and he seems to prefer the company of lady dogs. His biggest dream is a yard with his very own kiddie pool! Oscar is affectionate, silly, smart and eager to please. He also happens to be extremely adorable. He cannot wait to be living it up with a family of his own, one that will be dedicated to help him keep perfecting his skills!',
    petID: '37295817',
    type: 'Dog',
    photo: 'http://photos.petfinder.com/photos/pets/37295817/1/?bust=1496723522&width=500&-x.jpg' },
  { status: 'Available',
    age: 'Adult',
    size: 'L',
    breed: 'Labrador Retriever',
    name: 'Loki',
    sex: 'Male',
    description: 'There\'s something about black dogs. Though they are beautiful, they tend to get overlooked in the shelter. But if you could take a moment and visit Loki, you\'ll see that he is a total love-bug. He has that look that says, \'Want to have some fun together?\' Once you get him leashed up and out the door, he is full of life! He can lope around the ball fields with a big, goofy grin! No matter what he\'s doing, he seems very proud of himself as he struts his stuff. His true joyful nature comes out when he\'s outside having fun. His other favorite hobby is loving up on his humans. He is a very affectionate cuddlebug. He loves being around his favorite people, giving them kisses, cuddling on their laps and spooning in bed with them. He brings toys to his human friends for playtime, plays tug-o-war, chases tennis balls, and then does zoomies in the yard. He\'s a smart, treat motivated boy who already answers to a host of hand signal commands - including \'sit,\' \'lay down\' and \'shake.\' And he\'s crate-trained and seems house trained and is great in the car. If you\'ve got treats, he\'s willing to learn new tricks. Loki is a loving, loyal boy will be eager to please an active family and who can give him the affection he wants and will return in abundance. If that\'s not incentive enough, his adoption fee is paid. Won\'t you come visit him today? Please check out his Instagram @adoptloki.apa to learn more about Loki!',
    petID: '37295821',
    type: 'Dog',
    photo: 'http://photos.petfinder.com/photos/pets/37295821/1/?bust=1496723534&width=500&-x.jpg' },
  { status: 'Available',
    age: 'Adult',
    size: 'L',
    breed: 'Shepherd',
    name: 'Pinball',
    sex: 'Female',
    description: 'Sweet, relaxed and smart. This pretty lady has it all. Pinball is a great listener and is looking for a human who is ready to cuddle with her and teach her some more tricks. But don\'t be fooled- she\'s a smart girl and knows quite a few already. She\'s easy to please, and is always down for a cuddle, a pet, or even a walk. She\'s always ready to learn, and to love. Pinball\'s perfect home would be one with a big back yard for her to play in. And humans who like being active, or going on runs or on the trails would be a perfect fit. She\'s great walking on a leash, listens well and is in the Total Obedience Program. The Total Obedience Program (TOP) is modelled after the AKC\'s Canine Good Citizen (CGC) test. As a TOP dog, Pinball has a personalized training plan and works with a volunteer trainer several times a week to help her learn the skills to become the best dog she can be! She is learning skills like sit and down, walking nicely on leash, sitting calmly when approached by strangers or other dogs, staying in a sit or down until told \'free,\' and coming when called. Once Pinball successfully completes all the skills on her training plan she will be considered TOP Dog Ready! Pinball is working hard to become a wonderful pet and as a part of APA\'s Total Obedience Program you can work with APA staff to continue to build a training relationship with Pinball after adoption and master all the TOP dog skills together. Check out a video on APA\'s CGC program, on which the TOP was based: https://vimeo.com/89434193',
    petID: '37295827',
    type: 'Dog',
    photo: 'http://photos.petfinder.com/photos/pets/37295827/1/?bust=1496723549&width=500&-x.jpg' },
  { status: 'Available',
    age: 'Adult',
    size: 'XL',
    breed: 'Hound',
    name: 'Ziggy',
    sex: 'Male',
    description: 'If a spunky, young dog with a desire to learn is what you\'re looking for, come to Austin Pets Alive! to meet Ziggy. Imagine adopting a dog who already has the foundation of obedience - obeying sit, down, place (in progress), walking on leash. Ziggy is a very playful guy, and he loves to run, run and run some more. Ziggy is very treat-oriented, making training a fun time for you both. When walking on leash, he\'s sometimes so focused on his handler and the treat, he\'ll walk right into fences. Ziggy enjoys learning new things and is in the Total Obedience Program. The Total Obedience Program (TOP) is modelled after the AKC\'s Canine Good Citizen (CGC) test. As a TOP dog, Ziggy has a personalized training plan and works with a volunteer trainer several times a week to help him learn the skills to become the best dog he can be! He is learning skills like sit and down, walking nicely on leash, sitting calmly when approached by strangers or other dogs, staying in a sit or down until told \'free,\' and coming when called. Once Ziggy successfully completes all the skills on his training plan he will be considered TOP Dog Ready! Ziggy is working hard to become a wonderful pet and as a part of APA\'s Total Obedience Program you can work with APA staff to continue to build a training relationship with Ziggy after adoption and master all the TOP dog skills together. Check out a video on APA\'s CGC program, on which the TOP was based: https://vimeo.com/89434193 Ziggy is going to grow into his body and his manners; just you wait and see what training and love will do for him. He wants to be yours! This goofy boy will melt your heart and empty your treat pouch.',
    petID: '37295841',
    type: 'Dog',
    photo: 'http://photos.petfinder.com/photos/pets/37295841/1/?bust=1496723574&width=500&-x.jpg' },
  { status: 'Available',
    age: 'Adult',
    size: 'L',
    breed: 'Catahoula Leopard Dog',
    name: 'Spanky',
    sex: 'Male',
    description: 'In a word, quirky would be the best way to describe this little rascal. He\'s kind of like the Eddie Haskell of dogs. Always up to something and ready to get into some fun shenanigans with his best bud! He may be small in stature, but his personality is larger than life. This guy is a character, that\'s for sure! He may have a mischievous look in his eyes, but Spanky is really chill on the leash. While exploring the great outdoors, he likes to stay right by his human\'s side. He\'s very curious about his surroundings and is always ready for a fun adventure. Walking is a lot of fun, but what he most enjoys is lap time! This little dude wants to be in your lap more than anything. If you\'re looking for a dog that will shower you with affection, Spanky\'s your man. Once you pet his super soft brindle coat, you\'ll see that he is made for cuddling! When he\'s not canoodling with his humans, he\'s happy to entertain himself with toys. You should see him tossing toys up in the air and flopping around like a fish out of water. Graceful, he is not-but he owns his clumsiness like a boss! Like his alter ego, Eddie Haskell, Spanky is smart like a fox. He enjoys learning new things and is in the Total Obedience Program. The Total Obedience Program (TOP) is modelled after the AKC\'s Canine Good Citizen (CGC) test. As a TOP dog, Spanky has a personalized training plan and works with a volunteer trainer several times a week to help him learn the skills to become the best dog he can be! He is learning skills like sit and down, walking nicely on leash, sitting calmly when approached by strangers or other dogs, staying in a sit or down until told \'free,\' and coming when called. Once Spanky successfully completes all the skills on his training plan he will be considered TOP Dog Ready! Spanky is working hard to become a wonderful pet and as a part of APA\'s Total Obedience Program you can work with APA staff to continue to build a training relationship with Spanky after adoption and master all the TOP dog skills together. Check out a video on APA\'s CGC program, on which the TOP was based: https://vimeo.com/89434193 See more of this cutie on his own Storify page!: https://storify.com/SpookyGurl95/operationadoptspanky-at-austin-pets-alive',
    petID: '37295858',
    type: 'Dog',
    photo: 'http://photos.petfinder.com/photos/pets/37295858/1/?bust=1496723587&width=500&-x.jpg' },
  { status: 'Available',
    age: 'Senior',
    size: 'XL',
    breed: 'Staffordshire Bull Terrier',
    name: 'Marilla',
    sex: 'Female',
    description: 'Marilla is delightful in all the ways dogs can be; goofy, cuddly, and completely unaware of her size. Marilla loves two things more than anything else in this world, and those things are fetch and belly rubs. If she has a choice between a ball or a new friendly person to beg for rubs, she will agonize over it for a few moments. Usually she chooses the belly rubs. And if she can get some playtime in water, even better. She has been labeled the \'Mermaid of Lady Bird Lake\', as she can be spotted at this watering hole on a sunny day, swimming the day away. Our Marilla can paddle for days. Her default assumption when meeting new people is that they are new best friends, and they feel the same way about her. She cannot get close enough to people. She will wind herself all around you trying to get as many body parts touching as possible. Marilla would do best in a home where someone can be around most of the time, with a yard to play in. She seems house trained. She would be best around older kids, as she is very strong and her cuddles may be overwhelming for little ones. We haven\'t introduced her to cats yet. Marilla enjoys learning new things and is in the Total Obedience Program. The Total Obedience Program (TOP) is modelled after the AKC\'s Canine Good Citizen (CGC) test. As a TOP dog, Marilla has a personalized training plan and works with a volunteer trainer several times a week to help her learn the skills to become the best dog she can be! She is learning skills like sit and down, walking nicely on leash, sitting calmly when approached by strangers or other dogs, staying in a sit or down until told \'free,\' and coming when called. Once Marilla successfully completes all the skills on her training plan she will be considered TOP Dog Ready! Marilla is working hard to become a wonderful pet and as a part of APA\'s Total Obedience Program you can work with APA staff to continue to build a training relationship with Marilla after adoption and master all the TOP dog skills together. Check out a video on APA\'s CGC program, on which the TOP was based: https://vimeo.com/89434193 If you can handle mountains of instant and unconditional love, then please consider Marilla. She\'s been waiting for you.',
    petID: '37295861',
    type: 'Dog',
    photo: 'http://photos.petfinder.com/photos/pets/37295861/1/?bust=1496723599&width=500&-x.jpg' },
  { status: 'Available',
    age: 'Senior',
    size: 'XL',
    breed: 'Labrador Retriever',
    name: 'Boscoe',
    sex: 'Male',
    description: 'The best word to describe Boscoe? Enthusiastic. Whether it\'s showing off his skills, tossing around his toys, or making friends, Boscoe does it all with gusto. But even with all his pizzazz, he remains a gentleman when meeting new people. He sits, he shakes, he wiggles to your side with zeal! And don\'t let his gray hairs fool you; this newly minted senior has plenty of pep in his step and is still young at heart. Can\'t teach a dog old tricks? Boscoe is more than happy to prove you wrong. This savvy boy picks up on new skills in record time. He\'s got more than enough heart to repay the humans who love and care for him. He aims to please, and he aims high! Boscoe has a full repertoire of skills and would be thrilled to show you all he knows. This dapper gent is ready to win you over with his spunk and his charm!',
    petID: '37295873',
    type: 'Dog',
    photo: 'http://photos.petfinder.com/photos/pets/37295873/1/?bust=1496723611&width=500&-x.jpg' },
  { status: 'Available',
    age: 'Adult',
    size: 'XL',
    breed: 'Pit Bull Terrier',
    name: 'Monty',
    sex: 'Male',
    description: 'At first glance, it might appear that Monty is channeling his inner Eeyore. With those soulful puppy dog eyes and that prominent underbite, he has a way of pulling at our heartstrings. But don\'t be fooled! This fun-loving boy is all wiggles and wags when he\'s playing with toys or exploring the great outdoors. Runners and hikers, take note! if you\'re looking for the perfect trail companion, Monty is your boy. He goes out on the trail on a regular basis with his Virtual Foster friend. Together, they run side-by-side for miles. Bikers, strollers, dogs, cranky swans and other distractions don\'t phase him in the slightest. He truly is a fabulous workout buddy! So if you\'re looking for an athletic, sweet-natured, handsome boy, why not go the full Monty? If that face isn\'t enough to convince you to take him home immediately, we should also note that he has received rave reviews from his sleepover friend. He proved to be potty trained and a respectful houseguest. He\'s also an excellent snoozer and is content to lounge on the couch and keep you company for hours during Netflix marathons. In addition to being a top-notch lounger and trail companion, Monty is also in the Total Obedience Program. The Total Obedience Program (TOP) is modelled after the AKC\'s Canine Good Citizen (CGC) test. As a TOP dog, Monty has a personalized training plan and works with a volunteer trainer several times a week to help him learn the skills to become the best dog he can be! He is learning skills like sit and down, walking nicely on leash, sitting calmly when approached by strangers or other dogs, staying in a sit or down until told \'free,\' and coming when called. Once Monty successfully completes all the skills on his/her training plan he will be considered TOP Dog Ready! Monty is working hard to become a wonderful pet and as a part of APA\'s Total Obedience Program you can work with APA staff to continue to build a training relationship with Monty after adoption and master all the TOP dog skills together. Check out a video on APA\'s CGC program, on which the TOP was based: https://vimeo.com/89434193 So what do you say? Want to come visit this sweet boy today? We have no doubt he will make his forever family very happy one day! Follow Monty on Instagram! https://www.instagram.com/adopt_monty',
    petID: '37295882',
    type: 'Dog',
    photo: 'http://photos.petfinder.com/photos/pets/37295882/1/?bust=1496723624&width=500&-x.jpg' },
  { status: 'Available',
    age: 'Senior',
    size: 'XL',
    breed: 'Pit Bull Terrier',
    name: 'Chewy',
    sex: 'Male',
    description: 'Chewy can\'t decide what he loves the most - being scratched on the base of his tail or those wonderful tennis balls. This sweet boy, with his wiggly, bouncy walk, also loves getting attention and affection from his human friends. He has a playful, youthful spirit that makes him fun to take for walks, and he walks well on his leash. He\'s always up for playing fetch. Chewy enjoys learning new things and is in the Total Obedience Program. The Total Obedience Program (TOP) is modeled after the AKC\'s Canine Good Citizen (CGC) test. As a TOP dog, Chewy has a personalized training plan and works with a volunteer trainer several times a week to help him learn the skills to become the best dog he can be! He is learning skills like sit and down, walking nicely on leash, sitting calmly when approached by strangers or other dogs, staying in a sit or down until told \'free,\' drop those tennis balls when he brings them back and coming when called. Once Chewy successfully completes all the skills on his training plan he will be considered TOP Dog Ready! Chewy is working hard to become a wonderful pet and as a part of APA\'s Total Obedience Program you can work with APA staff to continue to build a training relationship with Chewy after adoption and master all the TOP dog skills together. Check out a video on APA\'s CGC program, on which the TOP was based: https://vimeo.com/89434193 Chewy will fit well into a home, possibly with older kids who can continue his training. A couch to nap on would be a bonus he\'d also love. Come visit and toss him a tennis ball! Follow Chewy on Instagram https://www.instagram.com/adopt_chewy/',
    petID: '37295884',
    type: 'Dog',
    photo: 'http://photos.petfinder.com/photos/pets/37295884/1/?bust=1497100358&width=500&-x.jpg' },
  { status: 'Available',
    age: 'Adult',
    size: 'XL',
    breed: { '$t': 'Labrador Retriever' },
    name: 'Chubbs',
    sex: 'Male',
    description: 'Chubbs is a dog who is in love with life. He adores chasing balls, exploring his world when out for a walk or run, and then settling down for all kinds of cuddling and love. He\'s not above telling you that you are not nearly finished with the belly rubs and assorted loving touches should you stop too soon! Chubbs is a people-pleasing ball full of love. He should take to training easily and is going to want to be an active participant in the life of his forever family. He has shown appropriate interest in other dogs he meets. He\'s a strong, athletic boy who would likely be a great running, hiking or walking buddy but will happily run off a lot of energy chasing those balls. He loves playing fetch and is quite talented at it. If you would like to play and cuddle to your heart\'s content with an appreciative, happy, goofy, adorable wonderful young dog who would like nothing more than to be yours forever, please come meet Chubbs real soon!',
    petID: '37295906',
    type: 'Dog',
    photo: 'http://photos.petfinder.com/photos/pets/37295906/1/?bust=1497100370&width=500&-x.jpg' },
  { status: 'Available',
    age: 'Senior',
    size: 'M',
    breed: 'Domestic Short Hair',
    name: 'Muffin',
    sex: 'Female',
    description: 'Affectionate, Sweet, Regal Muffin is a love muffin! She needs a little time to warm up to you, but once she does she will be looking to give \'rubby-rubs to her humans and will happily accept a good ear and chin rub in return. When you get home she will greet you at the door and she will guard your bed with every inch of her body when you\'re sleeping. This lovely senior lady really knows how to make you feel special! Muffin is low-maintenance and is very energetic for a cat her age. She loves to play, especially with her favorite toy which is simple, yet so entertaining...a good ol\' piece of string. She could give much younger cats lessons in proper string pouncing--none of that on the floor stuff, she catches hers while it\'s still up in the air! Muffin doesn\'t scratch on furniture and is a pro at using the litter box. She\'s quiet most of the time, but will start talking when she gets hungry. When it comes to being petted, she doesn\'t like for you to try and pet her from an angle she can\'t see and would prefer that you don\'t touch her pretty tortie tail. But, she is happy to accept love from you, as long as it\'s given on her terms! The ideal home for Muffin would include a patient adopter who is willing to give her time to acclimate to her new surroundings. Muffin would be comfortable with older kids who give her the space she needs, but younger children would be a bit much for this old gal. Muffin isn\'t happy when she sees the other cats in her foster home. So, she may have been the only kitty in her previous household and would likely do best as the solo cat. A low-energy dog would probably be fine if a slow introduction is made. Give Muffin the love and understanding she needs and she\'ll spend the rest of her life returning the favor tenfold to her most special and adored person...you! All APA! cats are fully vetted, spayed or neutered, and have updated vaccines and a microchip. Lifetime support is offered by our Cat Behavior Team. For further information or to meet Muffin, please email adopt@austinpetsalive.org.',
    petID: '37295934',
    type: 'Cat',
    photo: 'http://photos.petfinder.com/photos/pets/37295934/1/?bust=1496723661&width=500&-x.jpg' },
  { status: 'Available',
    age: 'Adult',
    size: 'XL',
    breed: 'Labrador Retriever',
    name: 'Roger',
    sex: 'Male',
    description: 'Roger came to the shelter as a stray, nervous and uncomfortable with being handled or walked. Today, this sweet boy is a big goof who loves prancing around on walks, running after toys, playing fetch and sitting down for a good scratch from his new human friends. All to say that Roger has come a long way! And he\'s ready to take his next trot into his new life in a new forever home. He\'s a easygoing, adventurous boy who walks well on his leash. He\'s answering to the sit, down, place and beg commands and is working on shake and drop. And he\'s doing well in playgroup with his new doggie friends. A house with a yard to play in and humans to give him the affection he loves would be ideal for Roger. Come visit and see if he\'s perfect for your home.',
    petID: '37295940',
    type: 'Dog',
    photo: 'http://photos.petfinder.com/photos/pets/37295940/1/?bust=1496723674&width=500&-x.jpg' },
  { status: 'Available',
    age: 'Adult',
    size: 'XL',
    breed: 'Pit Bull Terrier',
    name: 'Moose',
    sex: 'Male',
    description: 'In a word, Moose is magnificent! Just look at him and you\'ll see he\'s a sight to behold. This big lug of a dog has captured the hearts of many ladies here at the shelter. With his movie star good looks and strong, silent demeanor, it\'s easy to see how he became such a heartthrob! Good looks aside, Moose has so much to offer. Like James Dean, he\'s a bit of shy guy, but it won\'t take long for him to warm up and nuzzle you with that jowly face. He appears to be a serious dude in the kennel, but he morphs into a puppy when he\'s chasing his toys or taking a dip in the pool. His two passions in life are fetch and swimming. So if you\'re looking for an athletic, fun-loving guy, Moose is it! If you\'re a lover of the great outdoors, Moose is your perfect fit. He is a great walking and running companion. He goes out with his Virtual Foster friend every night for evening walks around the ball field. He\'s a gentleman on the leash and is learning some new skills. He\'s eager to please and will work hard for treats! Also, we should note that he appears to be potty trained and could potentially live in a home with a well-matched pup. So what do you say? Why not stop by APA today and see for yourself how much our Magnificent Moose has to offer? If you can look past his shyness, you\'ll see how much fun you both could have together!',
    petID: '37295949',
    type: 'Dog',
    photo: 'http://photos.petfinder.com/photos/pets/37295949/1/?bust=1496723686&width=500&-x.jpg' },
  { status: 'Available',
    age: 'Senior',
    size: 'L',
    breed: 'Domestic Short Hair',
    name: 'Rilo',
    sex: 'Female',
    description: 'Independent, Goofy, Hefty Want a cat that will make you laugh? Then Rilo is your gal! This chunky lady is a hoot, and she will make you chuckle to watch her chase her toys around. Rilo loves to watch the birds fly by the window and will take naps in the sunbeams. She also loves to eat (if you couldn\'t tell). She is a polite house guest and always goes in her litter box; she knows that lady cats must have good bathroom manners! Rilo isn\'t too much of a fan of other cats, but doesn\'t mind being around cats that respect her space. She can get over-stimulated during play, so we recommend a home with older children. If you want a goofy, playful, and independent companion, then Rilo is the perfect cat for you! All APA! cats and kittens are fully vetted, spayed or neutered, and have updated vaccines and a microchip. Lifetime support is offered by our Cat Behavior Team.?? For further information or to meet Rilo, please emailadopt@austinpetsalive.org.',
    petID: '37295953',
    type: 'Cat',
    photo: 'http://photos.petfinder.com/photos/pets/37295953/1/?bust=1496723698&width=500&-x.jpg' },
  { status: 'Available',
    age: 'Adult',
    size: 'XL',
    breed: 'German Shepherd Dog',
    name: 'Prieta',
    sex: 'Female',
    description: 'Prieta is a sweet girl who has been known to joyfully break out into running the cutest zoomies (sometimes while carrying a rope toy!) Prieta enjoys walks, wading in the water, and just sitting next to you with her head in your lap and watching the world go by. If there are two laps in the vicinity, she\'s an equal opportunity snuggler and will walk back and forth between the two to lean in for pets. She also likes toys (rope toys are her current favorite) and is happy to entertain herself with them. Prieta is a smart girl and learns new skills quickly. So smart, in fact, that she figured out the optimal way to get treats - by sticking her head in your treat pouch instead of waiting on you to slowly dole them out one at a time. Such a problem solver! She loves people, and once she knows and trusts you, she will be your friend for life. Prieta hopes to find a home with a loving, active person who wants to take her for those walks and jogs, then will curl up with her on the couch. If that sounds like you, come meet this beautiful girl.',
    petID: '37295960',
    type: 'Dog',
    photo: 'http://photos.petfinder.com/photos/pets/37295960/1/?bust=1497100396&width=500&-x.jpg' },
  { status: 'Available',
    age: 'Adult',
    size: 'M',
    breed: 'Domestic Short Hair',
    name: 'Humpty Dumpty',
    sex: 'Male',
    description: 'Humpty Dumpty neither sat on a great wall nor had a great fall that we are aware of so a name change may be in order! He is a really friendly guy who comes right up to new folks to say hello and absolutely LOVES to have his head scratched. Like LOVES it!! The opposite can be said about petting his side or scratching his backside. That he does NOT love and will let you know with a little side eye glance that is actually pretty cute despite his intention to be \'telling you how it is\'!! He isn\'t super cuddly and doesn\'t like to be picked up. He is a tall, lean fellow with really interesting markings especially around his eyes. Like any cat he loves finding a good, sunny spot for a nap. Humpty is a really playful guy - his favorite past time is playing with wand toy and anything with catnip. He is CRAZY for catnip!! He loves playing with other cats too so he would be great in a house with a feline friend. Not sure how he feels about dogs but he has seem some in his current location and seemed very interested so he might be okay with a canine companion too. All APA! cats are fully vetted, spayed or neutered, and have updated vaccines and a microchip. Lifetime support is offered by our Cat Behavior Team. For further information or to meet Humpty Dumpty, please email adopt@austinpetsalive.org.',
    petID: '37295983',
    type: 'Cat',
    photo: 'http://photos.petfinder.com/photos/pets/37295983/1/?bust=1496723723&width=500&-x.jpg' },
  { status: 'Available',
    age: 'Adult',
    size: 'L',
    breed: 'Domestic Short Hair',
    name: 'Sophia',
    sex: 'Female',
    description: 'Quiet, Affectionate, Lovely Sophia\'s gorgeous coat is a mixture of tabby orange, pure white and flourishes of black with a beauty mark that\'s to die for...no wonder she\'s the envy of all the kitties! But, Sophia\'s good looks have not gone to her head. She\'s such a sweetheart who longs for a sense of security and a warm, welcoming lap! Sophia is a bit shy with new people. But, give her a little time to get to know you and you\'ll see the uncertainty in those lovely green eyes change to adoration and trust. Then it\'s time to bring on the head scratches and to get ready for cozy times with this gentle angel happily snuggling by your side! Sophia has made efforts to make friends other cats at the shelter, so she would likely enjoy a kitty companion. No need to fret over what to feed her at meal time. Sophia keeps it simple! She needs to be on a special diet of Hill\'s C/D which is carried at local pet stores and is available online. Sophia is an all-around mellow kitty who dreams of the comfort a calm home and a loving human would surely bring. If you can imagine this lovely lady curled up beside you and warming your heart each and every day, come meet Sophia today! All APA! cats are fully vetted, spayed or neutered, and have updated vaccines and a microchip. Lifetime support is offered by our Cat Behavior Team. For further information or to meet Sophia, please email adopt@austinpetsalive.org.',
    petID: '37295985',
    type: 'Cat',
    photo: 'http://photos.petfinder.com/photos/pets/37295985/1/?bust=1496723734&width=500&-x.jpg' },
  { status: 'Available',
    age: 'Adult',
    size: 'M',
    breed: 'Domestic Short Hair',
    name: 'Luke Cage',
    sex: 'Male',
    description: 'Luke Cage has a temporary bit of ringworm, but a lifetime of love to give. Ringworm is a common, easily treatable skin condition! All APA! kitties with ringworm are currently adoptable with ZERO fee, a free course of medication, and unlimited support! Check out @austinpetsaliveringworm on Facebook to learn more and see the awesome kitties covered in this special; and feel free to write us at ringworm@austinpetsalive.org with any questions you may have. All APA! cats are fully vetted, spayed or neutered, and have updated vaccines and a microchip. Lifetime support is offered by our Cat Behavior Team. For further information or to meet Luke Cage, please email adopt@austinpetsalive.org.',
    petID: '37296035',
    type: 'Cat',
    photo: 'http://photos.petfinder.com/photos/pets/37296035/1/?bust=1496723747&width=500&-x.jpg' },
  { status: 'Available',
    age: 'Adult',
    size: 'L',
    breed: 'Domestic Short Hair',
    name: 'Hans Dorfler',
    sex: 'Male',
    description: 'Big, good looking, charming Hans Dorfler is a handsome charmer who\'s just a big softy at heart! He\'ll occasionally wrestle with his kitty roommates, though he often prefers to just watch them play. He likes attention when he initiates it. He can get overwhelmed at times by too much attention and petting, so he\'s probably not the best match for small kids and excitable dogs. He is a champion napper who will amuse you with his many \'I\'m soooo comfortable! napping positions. Hans had good litter box and scratching manners. He\'s definitely not into nail trims, though. He can be a bit vocal when it\'s time to eat. Hans Dorfler has been with us for several months now, and we know he\'d love to have his own forever home soon! He\'d do well in any relatively quiet home with people who understand cat body language for \'that\'s enough petting for now, thanks!\' He\'d probably like to have another kitty friend, too. Hans Dorfler has a temporary bit of ringworm, but a lifetime of love to give. Ringworm is a common, easily treatable skin condition! All APA! kitties with ringworm are currently adoptable with ZERO fee, a free course of medication, and unlimited support! Check out @austinpetsaliveringworm on Facebook to learn more and see the awesome kitties covered in this special; and contact us with any questions you may have. All APA! cats are fully vetted, spayed or neutered, and have updated vaccines and a microchip. Lifetime support is offered by our Cat Behavior Team. For further information or to meet Hans Dorfler, please email adopt@austinpetsalive.org.',
    petID: '37296036',
    type: 'Cat',
    photo: 'http://photos.petfinder.com/photos/pets/37296036/1/?bust=1496723759&width=500&-x.jpg' },
  { status: 'Available',
    age: 'Adult',
    size: 'L',
    breed: 'Domestic Short Hair',
    name: 'Blue Bonnet',
    sex: 'Female',
    description: 'Dainty, Polite, Charming It\'s the season for Blue Bonnet! This super sweet lady likes to be near you or snuggling by your side. She prefers lounging on the couch to playing with toys. She has a charming personality too. She\'ll give you a heart-melting look with her giant eyes, a soft head boop and top it all off with a darling meow. Blue Bonnet would probably be okay with quiet, gentle kids. She could live with other cats too-she\'s tolerant and pretty much keeps to her own around them. Blue Bonnet is also FeLV+ (Feline Leukemia Virus), which causes a weakened immune system and requires special care. APA! provides some medical assistance after adoption. Cats with FeLV typically have a shortened lifespan. Sterling is not contagious to people or dogs, but should live only with other FeLV+ cats. For more information, please contact APA! or read more by our Partner, Best Friends Animal Society: http://bestfriends.org/Resources/FAQs-About-Feline-Leukemia-Virus-FeLV Blue Bonnet is looking for a forever home with a soft bed to curl up on, a couch with a sunbeam for naps and a window to watch birds. And of course, plenty of love and affection. Blue Bonnet has a temporary bit of ringworm, but a lifetime of love to give. Ringworm is a common, easily treatable skin condition! All APA! kitties with ringworm are currently adoptable with ZERO fee, a free course of medication, and unlimited support! Check out @austinpetsaliveringworm on Facebook to learn more and see the awesome kitties covered in this special; and contact us with any questions you may have. All APA! cats are fully vetted, spayed or neutered, and have updated vaccines and a microchip. Lifetime support is offered by our Cat Behavior Team. For further information or to meet Blue Bonnet, please email adopt@austinpetsalive.org.',
    petID: '37296056',
    type: 'Cat',
    photo: 'http://photos.petfinder.com/photos/pets/37296056/1/?bust=1496723772&width=500&-x.jpg' },
  { status: 'Available',
    age: 'Senior',
    size: 'M',
    breed: 'Domestic Short Hair',
    name: 'Ginger',
    sex: 'Female',
    description: 'Mellow, Sweet, Calm Being a senior cat, Ginger would be the perfect companion cat for an older couple! She is mellow and tranquil. She might playfully bat at your pen now and then, but after that will have to take a nap. Her ideal home would be quiet and low-key. She doesn\'t need to sit in your lap, but she does appreciate being scratched and petted. When she\'s had enough, she will push your hand away. Okay, got it, Ginger! Smart girl. Previous to her stay with APA!, Ginger had been declawed. As a result of this she must remain an indoor cat. Which makes perfect sense, because what she wants is to quietly lounge around the house. She mostly ignores the other cats she has met, and we think she\'d be okay with older kids who respected her age and activity level. When she gets stressed out she may over groom herself, which is her way of saying, please lower the stress! So a home with rambunctious dogs would not be a good fit. Ginger is a dainty, little old lady with good litter manners. She is an easy cat to live with and to love. If you are looking for this kind of sweetness in your life, contact us today to arrange a meet & greet! All APA! cats are fully vetted, spayed or neutered, and have updated vaccines and a microchip. Lifetime support is offered by our Cat Behavior Team. For further information or to meet Ginger, please email adopt@austinpetsalive.org.',
    petID: '37296063',
    type: 'Cat',
    photo: 'http://photos.petfinder.com/photos/pets/37296063/1/?bust=1496723784&width=500&-x.jpg' },
  { status: 'Available',
    age: 'Senior',
    size: 'XL',
    breed: { '$t': 'Labrador Retriever' },
    name: 'Timmy',
    sex: 'Male',
    description: 'We don\'t know much about Timmy\'s past, but we know he\'s been through a lot. His tail is always wagging, and he looks at our volunteers with so much hope and love. But there\'s something holding him back from trusting 100%. He is a dog in need of real rescuing, and we\'re hoping there is a special person out there who can show him there\'s good things in store. Timmy loves to go on walks and is a great leash walker. He doesn\'t really like to be petted, but once he trusts you, he will sometimes lay his head in your lap and gaze at you adoringly. He doesn\'t do that with just anyone, so if you get The Look, you know you\'ve earned a special place in his heart. It might take some time to really forge a bond with Timmy, but once you do, we know it will be a friendship that you will never forget. Timmy is exactly the kind of dog APA! is here for. If you have room in your life to help a lost soul who really needs it, consider Timmy.',
    petID: '37296070',
    type: 'Dog',
    photo: 'http://photos.petfinder.com/photos/pets/37296070/1/?bust=1496723796&width=500&-x.jpg' },
  { status: 'Available',
    age: 'Adult',
    size: 'L',
    breed: 'Pit Bull Terrier',
    name: 'Lamar',
    sex: 'Male',
    description: 'Though Lamar will play and enjoys some play time, he\'s really all about affection and being close to those he loves. He does enjoy his walks and is great on his leash. When at playgroup, he cavorts for a little while, but then he\'s quite content to find his special friend or friends and settle in for some snuggle time. Apparently Lamar is a great kitchen companion. He\'s not opposed to trying new things, any or all, and is happy to clean up any kitchen mess made during this new recipe try out fun. And the look in his happy eyes will let you know, you\'ve found a winner of a new recipe. Lamar would be happiest in a home with adults or older children who understand the best relationships develop a little slowly then becoming enduring and strong. He might enjoy one doggy friend in the house as well. This boy is one happy go lucky and super affectionate guy. When he gets one-on-one time with his friends at the shelter, his tail won\'t stop wagging and he makes it known how grateful he is for attention and affection. This guy deserves his very own all the time snuggle partner/s. Come meet him and start that process of getting to know him as soon as you can get here. He\'s waiting to meet you and start that tail wagging just for you.',
    petID: '37296100',
    type: 'Dog',
    photo: 'http://photos.petfinder.com/photos/pets/37296100/1/?bust=1496723808&width=500&-x.jpg' },
  { status: 'Available',
    age: 'Adult',
    size: 'L',
    breed: 'Domestic Short Hair',
    name: 'Lamar',
    sex: 'Male',
    description: 'Handsome, Social, Big Lamar knows what he wants and where to get it! With a big personality, Lamar will seek out affection from his human friends and loves to cuddle with his feline counterparts. A fan of other adults cats, he prefers to be around a mature audience, so kittens and lots of over-stimulation are not his cup of tea. As an occasional participant in playtime, Lamar would love to be adopted into a home with another cat. Lamar will be vocal at chow time, but otherwise loves to ascend to the highest peaks in his vicinity for a great view. Lamar has a temporary bit of ringworm, but a lifetime of love to give. Ringworm is a common, easily treatable skin condition! All APA! kitties with ringworm are currently adoptable with ZERO fee, a free course of medication, and unlimited support! Check out @austinpetsaliveringworm on Facebook to learn more and see the awesome kitties covered in this special; and contact us with any questions you may have. All APA! cats are fully vetted, spayed or neutered, and have updated vaccines and a microchip. Lifetime support is offered by our Cat Behavior Team. For further information or to meet Lamar, please email adopt@austinpetsalive.org.',
    petID: '37296115',
    type: 'Cat',
    photo: 'http://photos.petfinder.com/photos/pets/37296115/1/?bust=1496723820&width=500&-x.jpg' },
  { status: 'Available',
    age: 'Adult',
    size: 'L',
    breed: 'Domestic Short Hair',
    name: 'Ryan',
    sex: 'Male',
    description: 'Quiet, Affectionate, Handsome Ryan didn\'t get enough attention in his previous home, and he is making up for lost time! As long as you approach him properly: quietly, slowly, sitting down, allowing him to come to you. And then it is obvious that he adores affection! He will sit in your lap and \'let\' you scratch his head and chin for hours; he will be reluctant to leave your warm and snuggly lap! Ryan has all he needs to be a super-friendly, awesome companion cat - now he just needs a human companion willing to take things slowly with him. Ryan is quite dashing, too, with the cluster of gray chest hairs amidst his rich, black coat: it looks like he is all dressed up, wearing a bow tie or ascot! Ryan and his foster brother, Stormy, have been pals for a while and do well together, even though Ryan is the bossy one in their relationship (and sometimes gets jealous with sharing your affection). Ryan would do well in a home with Stormy or another mellow kitty. To learn more about Stormy - https://www.austinpetsalive.org/adopt/available-cat-details/?ID=44055 In addition to playing with Stormy, Ryan is a big fan of wand toys! He will grab the wand toy and play tug-of-war with you. He is playful, but moderately so; not crazy-playful. The best home for Ryan would be quiet/low-traffic, with Stormy or another easy-going cat buddy, and adults/young adults; little kids would likely be too chaotic for him. He is about halfway to being a TOTAL lap cat, are you ready to help him go the rest of the distance? Contact us today to meet him! All APA! cats are fully vetted, spayed or neutered, and have updated vaccines and a microchip. Lifetime support is offered by our Cat Behavior Team. For further information or to meet Ryan, please email adopt@austinpetsalive.org.',
    petID: '37296117',
    type: 'Cat',
    photo: 'http://photos.petfinder.com/photos/pets/37296117/1/?bust=1496723833&width=500&-x.jpg' },
  { status: 'Available',
    age: 'Adult',
    size: 'L',
    breed: 'Domestic Short Hair',
    name: 'Frank',
    sex: 'Male',
    description: 'This face! Mister Frank is the most handsome Van cat, mostly white with black around the edges. His eyes are always sparkling and his whisker game is fierce. Despite his obvious excellence, Frank is a bit of a shy guy. He needs someone to dote on him and let him know how wonderful he is. Can you give this sweet boy the gentle love he seeks? Frank has a temporary bit of ringworm, but a lifetime of love to give. Ringworm is a common, easily treatable skin condition! All APA! kitties with ringworm are currently adoptable with ZERO fee, a free course of medication, and unlimited support! Check out @austinpetsaliveringworm on Facebook to learn more and see the awesome kitties covered in this special; and contact us with any questions you may have. All APA! cats are fully vetted, spayed or neutered, and have updated vaccines and a microchip. Lifetime support is offered by our Cat Behavior Team. For further information or to meet Frank, please email adopt@austinpetsalive.org.',
    petID: '37296121',
    type: 'Cat',
    photo: 'http://photos.petfinder.com/photos/pets/37296121/1/?bust=1496723845&width=500&-x.jpg' },
  { status: 'Available',
    age: 'Adult',
    size: 'M',
    breed: 'Domestic Short Hair',
    name: 'Stormy',
    sex: 'Male',
    description: 'Quiet, Shy, Playful Stormy is anything but - it\'s clear sailing with our Stormy! Stormy came from a home where he didn\'t get a lot of human interaction, but that didn\'t affect his super-sweet demeanor. He is not crazy about being picked up, and much prefers for you to approach him calmly and quietly and sit on the floor with him (because when you are standing over him, you are dauntingly tall). Then he will do a belly flop to make it easy as possible for you to pet him. He ESPECIALLY likes for you to scratch his chinny-chin-chin and rub his head. He was recently introduced to the brush, and has decided that\'s okay, too - so brush his coat and increase his bliss! Stormy is easy-going and meek with other cats, even his bossy foster brother, Ryan. Stormy would do well in a home with Ryan or with another chill cat who will let his sweet personality shine even brighter. To learn more about Ryan - https://www.austinpetsalive.org/adopt/available-cat-details/?ID=43962 Stormy is playful, so get your wand toys ready! Those get him energized, as well as chasing little balls around the house. He is young and eager to play, he just needs his patient human companion to go slowly with him. Stormy likes his wet food, so he needs to exercise to stay fit & healthy! The best home for Stormy would include Ryan or another chill cat buddy, and adult humans; young children would likely startle him. His home should be on the quiet and low-traffic side of active. Stormy is everything we love about cats. Contact us today to arrange a meet & greet! All APA! cats are fully vetted, spayed or neutered, and have updated vaccines and a microchip. Lifetime support is offered by our Cat Behavior Team. For further information or to meet Stormy, please email adopt@austinpetsalive.org.',
    petID: '37296147',
    type: 'Cat',
    photo: 'http://photos.petfinder.com/photos/pets/37296147/1/?bust=1496723857&width=500&-x.jpg' },
  { status: 'Available',
    age: 'Senior',
    size: 'M',
    breed: 'Domestic Short Hair',
    name: 'Many Toes',
    sex: 'Female',
    description: 'Chatty - Mellow - Lap Cat Many Toes got her unusual name from one of her most distinguished features -- she does indeed have many toes! We\'re not even sure just how many, that\'s how many toes she has. She is a polydactyl, which is just a fancy way of saying a cat with more toes than the usual amount. When you meet this sweet senior lady, you\'ll want to kiss all her little toes and you\'ll see why Earnest Hemingway had a special fondness for polydactyl cats. Many Toes is so happy to be loved on! She loves laps and adores chin scratches. She will purr and purr and lean into hands. Her favorite thing in the world is being pet, brushed, and fed all at the same time. She is chatty little old lady with a little old lady meow. She doesn\'t yell, and isn\'t super loud, but will hold a conversation with you. She is respectful towards other cats and would be fine as a second cat. Her experience with dogs is unknown, but she\'d likely get along fine with a calm or older dog. Older children would also be great companions for Many Toes. She mostly wants to sleep, eat and be loved, and will flourish in a calm house where she can chill with her favorite humans. Many Toes has Chronic Renal Disease, which means Many Toes\'s kidneys are not functioning as well as they once were. This condition is so common in older cats that APA! offers a special adoption package for them. Read more about renal failure and adoption details here: http://www.austinpetsalive.org/2016/03/lives-worth-saving-cats-in-renal-failure All APA! cats are fully vetted, spayed or neutered, and have updated vaccines and a microchip. Lifetime support is offered by our Cat Behavior Team. For further information or to meet Many Toes please email adopt@austinpetsalive.org.',
    petID: '37296291',
    type: 'Cat',
    photo: 'http://photos.petfinder.com/photos/pets/37296291/1/?bust=1496723869&width=500&-x.jpg' },
  { status: 'Available',
    age: 'Adult',
    size: 'XL',
    breed: 'Pit Bull Terrier',
    name: 'Bevo',
    sex: 'Male',
    description: 'Bevo is a super-friendly dog who is looking for a family that is ready to love him back! This young adult is in the prime of life, and he\'s looking to become a long-term companion for a lucky home. Did we mention he\'s friendly? He bonds quickly with new humans and becomes a very devoted friend. He loves getting a good petting session. Wagging his tail just isn\'t enough - he likes to wiggle his whole body! But he\'s not just a loverboy. He also enjoys getting in some exercise. He has a medium energy level, loves going on walks and makes a great walking partner. He\'s also very treat motivated. Not only does this make it easy for his handler to keep Bevo\'s focus on walks, but it also makes Bevo enthusiastic about training. He\'s a smart guy who already knows basic obedience skills and walks nicely on a leash. He loves to learn new tricks as long as there is a tasty morsel in it for him. He\'s been working hard with the behavior team would would love to show you all he\'s learned. A playful boy, Bevo also loves to be outside running around, so a home with a yard would be great for him. He would love to play chase and tag with his favorite people, and he\'ll even push a soccer ball around with them. And then indoors, he also loves being a couch potato. Bevo loves to play with his dog friends at the shelter, and he\'d love to have more playdates to continue to receive socialization (and exercise). He shows potential for living nicely with a cat in his forever home. A home with older children or all adults would be great for him. With some ongoing leadership and consistency, Bevo should turn into a great family dog. He\'ll keep smiles on everyone\'s face!',
    petID: '37296312',
    type: 'Dog',
    photo: 'http://photos.petfinder.com/photos/pets/37296312/1/?bust=1497100446&width=500&-x.jpg' },
  { status: 'Available',
    age: 'Adult',
    size: 'M',
    breed: 'Domestic Short Hair',
    name: 'Sak',
    sex: 'Female',
    description: 'Silly, Affectionate, Talkative Sak is a small tortoisehell with a big purr-sonality. This gorgeous, super soft kitty pretends to be a little shy at first, but only out of habit. Once you start petting her, she can\'t resist. She flops and rolls around and just purrs and purrs. And, she is now officially a lap cat! She loves to hop up on the couch and curl up between her foster parents or snuggle up on her foster dad\'s lap. Sak has a lot to say, and her vocabulary includes adorable trills, sweet little meows and a loud, long meow when she wants attention. She gets along well with the other kittens in her foster home and loves to play with them. She\'s especially good at chasing toys around the house, slipping and sliding on the wood floors. She also has a kleptomaniac side and tends to swipe any small object that makes a nice noise or rolls well when it is batted around. Her favorites are tweezers, allen wrenches and pecans (tweezers and allen wrenches are taken away from her immediately for safety!), and she has even been known to swipe cherry tomatoes. Sak and her brother, Coach, had a rough start to life, and after months in the shelter they have really begun to blossom in their foster home. They will need a patient adopter or adopters who can give them the time and space they will need to adjust to their new home. In return, their adopter(s) will be rewarded with loving slow blinks, head butts, enthusiastic purring, and hours of entertainment as their kittens explore and play. Ideally Sak and Coach would be adopted together, and they would also do well in a household with other cats. They would prefer a quiet, low-stress home without too much activity. For more pictures and videos of Sak and Coach, have a look at their foster family\'s Facebook page - https://www.facebook.com/AllTheKittiesFosters or Instagram account - https://www.instagram.com/allthekittiesfosters All APA! cats are fully vetted, spayed or neutered, and have updated vaccines and a microchip. Lifetime support is offered by our Cat Behavior Team. For further information or to meet Sak, please email adopt@austinpetsalive.org.',
    petID: '37296316',
    type: 'Cat',
    photo: 'http://photos.petfinder.com/photos/pets/37296316/1/?bust=1497100457&width=500&-x.jpg' },
  { status: 'Available',
    age: 'Adult',
    size: 'M',
    breed: 'Domestic Short Hair',
    name: 'Coach',
    sex: 'Male',
    description: 'Curious, Low-Key, Cat-Lover Coach is a gentle giant who absolutely adores other cats. Although he is a little shy and tentative at first, he is as curious as a cat can be. When not actively exploring and investigating, he\'s busy observing the goings-on around him, especially if there are birds to watch outside. He loves the company of the other kittens in his foster home, and they have helped boost his confidence. Although he\'s not a lap cat (yet!), he\'s tentatively testing the waters and is working toward half on/half off, and walking across laps. He loves pets and scratches, especially around his neck and ears and seeks out attention from his foster parents. He has a sweet, low, chirpy purr and is happy to share it with you. If you catch him in a particularly snuggly mood, he\'ll let you pet and kiss his belly and give you enthusiastic head bumps. He is a master at staring lovingly into your eyes. Coach and his sister, Sak, had a rough start to life, and after months in the shelter they have really begun to blossom in their foster home. They will need a patient adopter or adopters who can give them the time and space they will need to adjust to their new home. In return, their adopter(s) will be rewarded with loving slow blinks, head butts, enthusiastic purring, and hours of entertainment as their kittens explore and play. Ideally Coach and Sak would be adopted together, and they would also do well in a household with other cats. They would prefer a quiet, low-stress home without too much activity. For more pictures and videos of Coach and Sak, have a look at their foster family\'s Facebook page - https://www.facebook.com/AllTheKittiesFosters or Instagram account - https://www.instagram.com/allthekittiesfosters All APA! cats are fully vetted, spayed or neutered, and have updated vaccines and a microchip. Lifetime support is offered by our Cat Behavior Team. For further information or to meet Coach, please email adopt@austinpetsalive.org.',
    petID: '37296318',
    type: 'Cat',
    photo: 'http://photos.petfinder.com/photos/pets/37296318/1/?bust=1497100468&width=500&-x.jpg' },
  { status: 'Available',
    age: 'Adult',
    size: 'L',
    breed: { '$t': 'Labrador Retriever' },
    name: 'Marmalade',
    sex: 'Female',
    description: 'If you\'re looking for a dog to make you smile, you found her. From the tips of ears to the tip of her tail, Marmalade knows how to have fun. She\'s an expert with a tennis ball, whether it\'s fetching with her human or rolling it around for herself. Her favorite game is burying them in muddy puddles and kiddie pools. Bonus points for the squeaky kind! Marmalade is the kind of dog who could possibly live with another dog, but would also be happy as an only child. But as long as there are enough treats to go around, that\'s what really matters. Marmalade is a sweet girl who takes a little extra time to really trust new people, but your patience will pay off 10 times over. She will reward you with unbridled joy and the sweetest kisses. So if you want a wiggly butt to greet you at the end of the day, look no further!',
    petID: '37296321',
    type: 'Dog',
    photo: 'http://photos.petfinder.com/photos/pets/37296321/1/?bust=1496723921&width=500&-x.jpg' },
  { status: 'Available',
    age: 'Senior',
    size: 'XL',
    breed: 'Boxer',
    name: 'Brasco',
    sex: 'Male',
    description: 'Brasco has made an exciting discovery - those tennis balls are really fun to chase. So he brings them back and drops at his person\'s feet on command so he can fetch them all over again. This happy, bouncy boy loves to romp and play. And outdoors he loves to explore with many, many sniffs. And then he wants to be with his human friends, getting as close to them as possible, curling his entire body against them. Brasco has lived with kids in the past. He walks well on his leash, seems crate trained and is reported to be house trained. And he\'s a gentle taker of those treats he loves. Brasco enjoys learning new things and is in the Total Obedience Program. The Total Obedience Program (TOP) is modelled after the AKC\'s Canine Good Citizen (CGC) test. As a TOP dog, Brasco has a personalized training plan and works with a volunteer trainer several times a week to help him learn the skills to become the best dog he can be! He is learning skills like sit and down, walking nicely on leash, sitting calmly when approached by strangers or other dogs, staying in a sit or down until told \'free,\' and coming when called. Once Brasco successfully completes all the skills on his training plan he will be considered TOP Dog Ready! Brasco is working hard to become a wonderful pet and as a part of APA\'s Total Obedience Program you can work with APA staff to continue to build a training relationship with Brasco after adoption and master all the TOP dog skills together. Check out a video on APA\'s CGC program, on which the TOP was based: https://vimeo.com/89434193 This cheerful boy may do best as the only pet in a home where he can get abundant love. He promises to return it many times over.',
    petID: '37296383',
    type: 'Dog',
    photo: 'http://photos.petfinder.com/photos/pets/37296383/1/?bust=1497100483&width=500&-x.jpg' },
  { status: 'Available',
    age: 'Adult',
    size: 'XL',
    breed: 'Pit Bull Terrier',
    name: 'Sam',
    sex: 'Male',
    description: 'He is Sam! Sam is a happy, healthy dog in the prime of life. He\'d love to meet his new family and become a long-term companion. Sam can take a few minutes to warm up to new faces. We know the feeling. But once he knows and trusts you, he truly is man\'s (or woman\'s) best friend. We\'re wondering how his tail is still attached, with all the wagging it does every time he spies his favorite volunteers. After he feels comfortable he loves to come up for some petting. Sam has a medium energy level. He definitely enjoys a good romp now and then, but he also likes to get in plenty of beauty sleep. We think Sam would do best in a home with adults or with older children. He\'ll definitely benefit from a family who can provide him with both mental and physical stimulation and ongoing training. He promises to make the learning fun for everyone! Sam is a good playmate for most dogs. If you\'ve already got a dog in your home, we\'d be happy to introduce them to make sure they would be compatible housemates. But Sam isn\'t just a good-time Charlie. He\'s shown himself to be a smart dog and knows all of his basic commands. Often he\'ll ask you for instructions by waving his paws at you. Sam is in the Total Obedience Program. The Total Obedience Program (TOP) is modelled after the AKC\'s Canine Good Citizen (CGC) test. As a TOP dog, Sam has a personalized training plan and works with a volunteer trainer several times a week to help him learn the skills to become the best dog he can be! He is learning skills like sit and down, walking nicely on leash, sitting calmly when approached by strangers or other dogs, staying in a sit or down until told \'free,\' and coming when called. Once Sam successfully completes all the skills on his training plan he will be considered TOP Dog Ready! Sam is working hard to become a wonderful pet and as a part of APA\'s Total Obedience Program you can work with APA staff to continue to build a training relationship with Sam after adoption and master all the TOP dog skills together. Check out a video on APA\'s CGC program, on which the TOP was based: https://vimeo.com/89434193',
    petID: '37296403',
    type: 'Dog',
    photo: 'http://photos.petfinder.com/photos/pets/37296403/1/?bust=1496723945&width=500&-x.jpg' },
  { status: 'Available',
    age: 'Adult',
    size: 'M',
    breed: 'Domestic Short Hair',
    name: 'Sao Paulo',
    sex: 'Female',
    description: 'Bright, Sweet, Shy Sao Paulo is your classic introverted free spirit. She can be a bit shy at first, but she makes fast, loyal friends out of everyone she meets. Her sweet personality is so infectious that Sao Paulo leads a pack of kitties in her shelter! She even bathes her kitty friends. Sao Paulo enjoys exploring her surroundings and discovering new nooks and crannies to hang out in. When she isn\'t playing around with her kitty friends she\'s an independent free spirit who enjoys doing her own thing. Don\'t let Sao Paulo\'s initial shyness scare you away, because with just a few chin scratches she melts and becomes an immediate friend. Sao Paulo\'s ideal home would have another cat or two to hang out with and plenty of space to explore the great indoors. If this sounds like you, don\'t hesitate to meet her today! All APA! cats are fully vetted, spayed or neutered, and have updated vaccines and a microchip. Lifetime support is offered by our Cat Behavior Team. For further information or to meet Sao Paulo, please email adopt@austinpetsalive.org.',
    petID: '37296409',
    type: 'Cat',
    photo: 'http://photos.petfinder.com/photos/pets/37296409/1/?bust=1496723957&width=500&-x.jpg' },
  { status: 'Available',
    age: 'Adult',
    size: 'M',
    breed: 'Domestic Short Hair',
    name: 'San Juan',
    sex: 'Female',
    description: 'Quiet, reserved, independent San Juan is a pretty little black and white tuxedo girl. This little lady knows what she wants, and likes to do her own thing. She especially loves climbing, perching up high, and exploring hidey holes. She occasionally enjoys hanging out with her other kitty friends, but will then want some alone time. San Juan is still shy and wary of adults, kids, and dogs. She may slowly warm up to adults as she gains trust in them and in her environment. She has good litter and scratching manners, but we do not even speak of nail trims, let alone attempt them. She will run and hide if she sees you with nail clippers. She\'s pretty quiet, though she will occasionally meow to remind you that it\'s time for breakfast. San Juan would do best in a quiet home with a cat-experienced adult or two who can gently encourage her to keep coming out of his shell while still respecting her independence. All APA! cats are fully vetted, spayed or neutered, and have updated vaccines and a microchip. Lifetime support is offered by our Cat Behavior Team. For further information or to meet San Juan, please email adopt@austinpetsalive.org.',
    petID: '37296428',
    type: 'Cat',
    photo: 'http://photos.petfinder.com/photos/pets/37296428/1/?bust=1496723969&width=500&-x.jpg' },
  { status: 'Available',
    age: 'Adult',
    size: 'XL',
    breed: 'Catahoula Leopard Dog',
    name: 'Chewbacca',
    sex: 'Male',
    description: 'Like his namesake, Chewbacca is ready to have his person\'s back. He loves his human friends. And unlike his namesake, Chewbacca is a very cuddly and super soft boy who has done well with other dogs in playgroup. He\'s content to go for walks with his people. And he really loves chairs - happy to sit in a chair next to his people, leaning against them. This sweet, smart boy is reported to be crate and house trained. Come visit and see if your house is his next destination!',
    petID: '37296468',
    type: 'Dog',
    photo: 'http://photos.petfinder.com/photos/pets/37296468/1/?bust=1496723981&width=500&-x.jpg' }
      ]);
    });
};
